service: default
runtime: python37

basic_scaling:
    max_instances: 16
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 1

entrypoint: gunicorn -b 0.0.0.0:$PORT main:server