service: default
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 2
    disk_size_gb: 1

entrypoint: gunicorn -b 0.0.0.0:8080 main:server --timeout 120